apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: ${IMAGE}:${VERSION}
        ports:
        - containerPort: 3000
